name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Gradle 8.1.1
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.1.1'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Build project & run unit tests
      run: ./gradlew build

    - name: Assemble Debug APK
      run: ./gradlew assembleDebug

    - name: List APKs
      run: find app/build/outputs -name "*.apk" -type f

    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30

    - name: Create GitHub Release Summary
      run: |
        echo "## ✅ Android Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Kotlin/Java build completed" >> $GITHUB_STEP_SUMMARY
        echo "- 📱 Debug APK uploaded to Artifacts" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Download APK" >> $GITHUB_STEP_SUMMARY
        echo "Check the 'Artifacts' section of this workflow run to download the APK." >> $GITHUB_STEP_SUMMARY
        
