name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Build project
      run: ./gradlew build

    - name: Assemble Debug APK
      run: ./gradlew assembleDebug

    - name: List APKs
      run: find app/build/outputs -name "*.apk" -type f

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30

    - name: Create Build Summary
      run: |
        echo "## ✅ Android CI Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- 🔧 JDK 11 with Gradle Build" >> $GITHUB_STEP_SUMMARY
        echo "- 📦 APK generated and uploaded" >> $GITHUB_STEP_SUMMARY
        echo "- 🔗 Check 'Artifacts' section above to download the APK." >> $GITHUB_STEP_SUMMARY
        
